In [1]:
import pandas as pd
import numpy as np
import chardet

In [3]:
file = 'Speed+Dating+Data.csv'

In [4]:
# detect file encoding

with open(file, 'rb') as f:
    data = f.read()

# Detect the encoding
result = chardet.detect(data)
print(result['encoding'])

Windows-1252

In [5]:
data = pd.read_csv(file, encoding=result['encoding'])
df = pd.DataFrame(data)

In [6]:
df.sample(30)

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
3519,246,4.0,1,8,1,10,9,3,3.0,6,...,7.0,7.0,7.0,7.0,5.0,7.0,5.0,6.0,5.0,6.0
4937,332,1.0,1,2,1,13,10,6,6.0,3,...,5.0,10.0,7.0,7.0,10.0,5.0,9.0,6.0,5.0,10.0
1995,148,7.0,0,13,2,7,16,2,2.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4021,273,1.0,1,2,2,11,21,17,17.0,9,...,7.0,6.0,6.0,6.0,6.0,7.0,9.0,8.0,7.0,9.0
3156,221,8.0,1,16,2,9,20,12,7.0,6,...,6.0,8.0,9.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN
8152,542,12.0,1,24,2,21,22,17,6.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7107,481,1.0,1,2,2,19,15,1,16.0,2,...,8.0,7.0,9.0,8.0,6.0,8.0,8.0,9.0,8.0,7.0
7661,520,12.0,0,23,2,21,22,9,9.0,21,...,8.0,9.0,9.0,7.0,5.0,7.0,9.0,7.0,6.0,6.0
2367,171,14.0,1,28,2,7,16,1,1.0,1,...,12.0,12.0,12.0,12.0,12.0,NaN,NaN,NaN,NaN,NaN
3665,256,5.0,0,9,2,11,21,7,7.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7810,527,19.0,0,37,2,21,22,13,13.0,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6760,449,10.0,1,20,2,17,11,6,8.0,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5065,343,3.0,0,5,2,14,18,8,8.0,15,...,7.0,9.0,9.0,9.0,9.0,6.0,9.0,9.0,10.0,9.0
6273,407,11.0,1,22,2,15,18,14,5.0,10,...,7.0,8.0,8.0,6.0,8.0,7.0,7.0,6.0,5.0,6.0
6292,408,12.0,1,24,2,15,18,13,7.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,76,1.0,0,1,2,4,18,5,NaN,15,...,6.0,6.0,8.0,6.0,3.0,NaN,NaN,NaN,NaN,NaN
1662,112,1.0,0,1,1,5,10,6,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1671,113,2.0,0,3,1,5,10,9,NaN,2,...,8.0,9.0,9.0,10.0,7.0,NaN,NaN,NaN,NaN,NaN
7671,520,12.0,0,23,2,21,22,9,9.0,12,...,8.0,9.0,9.0,7.0,5.0,7.0,9.0,7.0,6.0,6.0
653,47,8.0,1,16,2,2,19,11,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4712,312,5.0,1,10,2,12,14,13,13.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093,80,5.0,0,9,2,4,18,14,NaN,3,...,8.0,8.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN
5332,358,18.0,0,35,2,14,18,18,18.0,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994,148,7.0,0,13,2,7,16,2,2.0,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3402,233,20.0,1,40,2,9,20,15,11.0,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2960,211,18.0,0,35,2,9,20,7,7.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5420,362,2.0,1,4,2,14,20,6,6.0,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2243,163,6.0,1,12,2,7,16,11,11.0,1,...,7.0,7.0,8.0,7.0,8.0,NaN,NaN,NaN,NaN,NaN
3126,219,6.0,1,12,2,9,20,10,2.0,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3626,254,3.0,0,5,2,11,21,12,12.0,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.describe(include='all')

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,...,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,...,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,...,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,...,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,...,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,...,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,...,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,...,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [8]:
df.columns

Index(['iid', 'id', 'gender', 'idg', 'condtn', 'wave', 'round', 'position',
       'positin1', 'order',
       ...
       'attr3_3', 'sinc3_3', 'intel3_3', 'fun3_3', 'amb3_3', 'attr5_3',
       'sinc5_3', 'intel5_3', 'fun5_3', 'amb5_3'],
      dtype='object', length=195)

In [9]:
df.shape

(8378, 195)

In [11]:
df.head(1000)

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,74,9.0,1,18,1,3,10,2,NaN,7,...,7.0,9.0,8.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN
996,74,9.0,1,18,1,3,10,10,NaN,5,...,7.0,9.0,8.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN
997,74,9.0,1,18,1,3,10,1,NaN,6,...,7.0,9.0,8.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN
998,75,10.0,1,20,1,3,10,5,NaN,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,75,10.0,1,20,1,3,10,4,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN