In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import chardet

In [2]:
file = 'Speed+Dating+Data.csv'

In [3]:
# detect file encoding

with open(file, 'rb') as f:
    data = f.read()

# Detect the encoding
result = chardet.detect(data)
print(result['encoding'])

Windows-1252

In [4]:
data = pd.read_csv(file, encoding=result['encoding'])
df = pd.DataFrame(data)

In [5]:
df.sample(30)

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
2007,148,7.0,0,13,2,7,16,2,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1521,104,11.0,1,22,2,4,18,2,NaN,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7006,474,9.0,0,17,2,19,15,8,9.0,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
769,53,14.0,1,28,2,2,19,16,NaN,4,...,8.0,8.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN
3090,218,5.0,1,10,2,9,20,5,19.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6440,417,2.0,0,3,1,16,8,8,8.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2650,196,3.0,0,5,2,9,20,5,5.0,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5529,368,8.0,1,16,2,14,20,10,10.0,8,...,6.0,6.0,8.0,7.0,5.0,6.0,5.0,7.0,7.0,6.0
137,14,4.0,1,8,1,1,10,10,NaN,8,...,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN
4044,274,2.0,1,4,2,11,21,15,15.0,9,...,9.0,9.0,9.0,9.0,9.0,8.0,8.0,8.0,9.0,8.0
5887,386,8.0,0,15,2,15,19,14,14.0,10,...,7.0,8.0,8.0,7.0,7.0,6.0,7.0,7.0,6.0,7.0
5607,372,12.0,1,24,2,14,20,9,9.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4276,285,13.0,1,26,2,11,21,19,19.0,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6092,397,1.0,1,2,2,15,18,12,4.0,9,...,7.0,8.0,10.0,8.0,10.0,7.0,7.0,9.0,8.0,10.0
4059,275,3.0,1,6,2,11,21,5,5.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,23,3.0,0,5,2,2,16,3,NaN,15,...,5.0,7.0,8.0,6.0,8.0,NaN,NaN,NaN,NaN,NaN
8287,548,18.0,1,36,2,21,22,19,9.0,11,...,8.0,9.0,9.0,9.0,9.0,8.0,9.0,9.0,9.0,7.0
7116,482,2.0,1,4,2,19,15,3,15.0,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6150,400,4.0,1,8,2,15,18,2,11.0,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3272,227,14.0,1,28,2,9,20,14,4.0,11,...,7.0,9.0,9.0,8.0,9.0,NaN,NaN,NaN,NaN,NaN
6155,400,4.0,1,8,2,15,18,1,11.0,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1053,78,3.0,0,5,2,4,18,16,NaN,12,...,7.0,7.0,7.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN
7733,523,15.0,0,29,2,21,22,5,5.0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2586,191,8.0,1,16,1,8,10,6,10.0,7,...,7.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
5306,356,16.0,0,31,2,14,18,4,4.0,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1906,142,1.0,0,1,2,7,16,9,9.0,11,...,9.0,12.0,12.0,12.0,7.0,NaN,NaN,NaN,NaN,NaN
5944,389,11.0,0,21,2,15,19,2,2.0,17,...,8.0,10.0,8.0,10.0,6.0,8.0,8.0,7.0,8.0,4.0
3832,264,13.0,0,25,2,11,21,15,15.0,17,...,8.0,7.0,9.0,8.0,7.0,8.0,8.0,8.0,8.0,6.0
30,4,4.0,0,7,1,1,10,6,NaN,3,...,6.0,5.0,6.0,8.0,5.0,NaN,NaN,NaN,NaN,NaN
6274,407,11.0,1,22,2,15,18,13,5.0,9,...,7.0,8.0,8.0,6.0,8.0,7.0,7.0,6.0,5.0,6.0

In [6]:
df.describe(include='all')

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,...,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,...,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,...,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,...,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,...,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,...,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,...,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,...,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [7]:
df.columns

Index(['iid', 'id', 'gender', 'idg', 'condtn', 'wave', 'round', 'position',
       'positin1', 'order',
       ...
       'attr3_3', 'sinc3_3', 'intel3_3', 'fun3_3', 'amb3_3', 'attr5_3',
       'sinc5_3', 'intel5_3', 'fun5_3', 'amb5_3'],
      dtype='object', length=195)

In [8]:
df.shape

(8378, 195)

In [9]:
df.head(1000)

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,74,9.0,1,18,1,3,10,2,NaN,7,...,7.0,9.0,8.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN
996,74,9.0,1,18,1,3,10,10,NaN,5,...,7.0,9.0,8.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN
997,74,9.0,1,18,1,3,10,1,NaN,6,...,7.0,9.0,8.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN
998,75,10.0,1,20,1,3,10,5,NaN,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,75,10.0,1,20,1,3,10,4,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Différencier le sexe de chaque participant.e

In [12]:
unique = df[['iid', 'gender']].drop_duplicates()
unique['genre'] = unique['gender'].map({0: 'Femmes', 1: 'Hommes'})

unique.sample(30)

      iid  gender   genre
2688  198       0  Femmes
988    74       1  Hommes
4648  308       1  Hommes
4746  315       1  Hommes
1871  137       1  Hommes
6804  454       0  Femmes
6122  399       1  Hommes
4326  288       1  Hommes
6784  452       1  Hommes
100    11       1  Hommes
2088  154       0  Femmes
170    18       1  Hommes
4954  334       1  Hommes
2708  199       0  Femmes
2648  196       0  Femmes
440    36       0  Femmes
878    63       0  Femmes
3801  263       0  Femmes
908    66       1  Hommes
2248  164       1  Hommes
7740  524       0  Femmes
5276  355       0  Femmes
4760  316       1  Hommes
3028  215       1  Hommes
7011  475       0  Femmes
6374  413       1  Hommes
4690  311       1  Hommes
1098   81       0  Femmes
6488  424       1  Hommes
6524  430       0  Femmes

In [15]:
counts = unique['genre'].value_counts().reset_index()
counts.columns = ['genre', 'count']
counts['pourcentage'] = (counts['count'] / counts['count'].sum() * 100).round(1)

counts.head()

    genre  count  pourcentage
0  Hommes    277         50.3
1  Femmes    274         49.7

In [20]:
fig = px.pie(
    counts,
    values='count',
    names='genre',
    title='Répartition Femmes/ Hommes',
    color='genre',
    color_discrete_map={'Femmes': '#D4537E', 'Hommes': '#378ADD'},
    hole=0.5
)
 
fig.update_traces(
    texttemplate='%{label}<br>%{value} (%{percent})',
    textposition='outside'
)
 
fig.update_layout(
    showlegend=False,
    title_font_size=18,
    margin=dict(t=60, b=40, l=40, r=40)
)
 
fig.show()